### ISSUE TITLE
Configure multilanguage

### ISSUE THREAD

**Issue by adrianq** [EyeSeeTea/dataset-recoding-blessed#3]
multilingual terms in different languages: Spanish, French and Arabic.

**Comment by adrianq** [comment]
@troyel Can you confirm this is actually needed for the dataset-recoding app?

**Comment by troyel** [comment]
Hi, having support for multiple languages/translations is preferable but not critical. So depends a little on how much work is involved in adding this support.

**Comment by adrianq** [comment]
it is quite straightforward. Multi-language is already supported in the app. We just need to add the files and connect it to the multilanguage server. Thanks!
